// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_Alvaro_20190269.DAL;

namespace P2_AP1_Alvaro_20190269.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_Alvaro_20190269.Entidades.TiposDeTareas", b =>
                {
                    b.Property<int>("TipoDeTareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("TiempoAcomulado")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoDeTareaId");

                    b.ToTable("TiposDeTareas");

                    b.HasData(
                        new
                        {
                            TipoDeTareaId = 1,
                            Nombre = "Analisis",
                            TiempoAcomulado = 0
                        },
                        new
                        {
                            TipoDeTareaId = 2,
                            Nombre = "Diseno",
                            TiempoAcomulado = 0
                        },
                        new
                        {
                            TipoDeTareaId = 3,
                            Nombre = "Programacion",
                            TiempoAcomulado = 0
                        },
                        new
                        {
                            TipoDeTareaId = 4,
                            Nombre = "Prueba",
                            TiempoAcomulado = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
